In [3]:
import os

print(os.listdir("../data"))

['cleaned_data.csv', 'SampleSuperstore.csv']

In [4]:
import pandas as pd
import sqlite3

df = pd.read_csv("../data/SampleSuperstore_Cleaned.csv")

print(df.shape)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/SampleSuperstore_Cleaned.csv'

In [5]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles in data folder:")
print(os.listdir("../data"))

print("\nFiles in notebooks folder:")
print(os.listdir("."))

Current folder:
c:\Users\Jayasri\OneDrive\Desktop\python folder\apexplanet-data-analytics\notebooks

Files in data folder:
['cleaned_data.csv', 'SampleSuperstore.csv']

Files in notebooks folder:
['Task1_EDA.ipynb', 'Task2_SQL_Analysis.ipynb']

In [6]:
import pandas as pd
import sqlite3

df = pd.read_csv("../data/cleaned_data.csv")

print("Dataset loaded successfully!")
print("Rows and columns:", df.shape)

df.head()

Dataset loaded successfully!
Rows and columns: (5, 9)

,Order ID,Customer Name,Category,Sub-Category,Region,Sales,Quantity,Profit,Order Date
0,1001,Rahul,Furniture,Chair,East,2500,2,500,2026-01-10
1,1002,Priya,Technology,Laptop,West,45000,1,8000,2026-01-12
2,1003,Kiran,Office Supplies,Paper,South,800,10,100,2026-01-15
3,1004,Sneha,Technology,Phone,North,18000,2,3000,2026-01-18
4,1005,Arjun,Furniture,Table,East,7000,1,900,2026-01-20

In [7]:
print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       5 non-null      int64
 1   Customer Name  5 non-null      str
 2   Category       5 non-null      str
 3   Sub-Category   5 non-null      str
 4   Region         5 non-null      str
 5   Sales          5 non-null      int64
 6   Quantity       5 non-null      int64
 7   Profit         5 non-null      int64
 8   Order Date     5 non-null      str
dtypes: int64(4), str(5)
memory usage: 492.0 bytes

In [9]:
conn = sqlite3.connect("../data/superstore.db")

df.to_sql(
    "superstore",
    conn,
    if_exists="replace",
    index=False
)

print("superstore.db created successfully!")

superstore.db created successfully!

In [10]:
query = "SELECT * FROM superstore LIMIT 5;"

result = pd.read_sql(query, conn)

result

,Order ID,Customer Name,Category,Sub-Category,Region,Sales,Quantity,Profit,Order Date
0,1001,Rahul,Furniture,Chair,East,2500,2,500,2026-01-10
1,1002,Priya,Technology,Laptop,West,45000,1,8000,2026-01-12
2,1003,Kiran,Office Supplies,Paper,South,800,10,100,2026-01-15
3,1004,Sneha,Technology,Phone,North,18000,2,3000,2026-01-18
4,1005,Arjun,Furniture,Table,East,7000,1,900,2026-01-20

In [11]:
import pandas as pd
import sqlite3

df = pd.read_csv("../data/cleaned_data.csv")

print("Dataset loaded successfully!")
print("Rows and columns:", df.shape)

df.head()

Dataset loaded successfully!
Rows and columns: (5, 9)

,Order ID,Customer Name,Category,Sub-Category,Region,Sales,Quantity,Profit,Order Date
0,1001,Rahul,Furniture,Chair,East,2500,2,500,2026-01-10
1,1002,Priya,Technology,Laptop,West,45000,1,8000,2026-01-12
2,1003,Kiran,Office Supplies,Paper,South,800,10,100,2026-01-15
3,1004,Sneha,Technology,Phone,North,18000,2,3000,2026-01-18
4,1005,Arjun,Furniture,Table,East,7000,1,900,2026-01-20

In [12]:
print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       5 non-null      int64
 1   Customer Name  5 non-null      str
 2   Category       5 non-null      str
 3   Sub-Category   5 non-null      str
 4   Region         5 non-null      str
 5   Sales          5 non-null      int64
 6   Quantity       5 non-null      int64
 7   Profit         5 non-null      int64
 8   Order Date     5 non-null      str
dtypes: int64(4), str(5)
memory usage: 492.0 bytes

In [14]:
conn = sqlite3.connect("../data/superstore.db")

df.to_sql(
    "superstore",
    conn,
    if_exists="replace",
    index=False
)

print("superstore.db created successfully!")

superstore.db created successfully!

In [15]:
query = "SELECT * FROM superstore LIMIT 5;"
result = pd.read_sql(query, conn)
result

,Order ID,Customer Name,Category,Sub-Category,Region,Sales,Quantity,Profit,Order Date
0,1001,Rahul,Furniture,Chair,East,2500,2,500,2026-01-10
1,1002,Priya,Technology,Laptop,West,45000,1,8000,2026-01-12
2,1003,Kiran,Office Supplies,Paper,South,800,10,100,2026-01-15
3,1004,Sneha,Technology,Phone,North,18000,2,3000,2026-01-18
4,1005,Arjun,Furniture,Table,East,7000,1,900,2026-01-20

In [16]:
query = """
SELECT *
FROM superstore
LIMIT 10;
"""

pd.read_sql(query, conn)

,Order ID,Customer Name,Category,Sub-Category,Region,Sales,Quantity,Profit,Order Date
0,1001,Rahul,Furniture,Chair,East,2500,2,500,2026-01-10
1,1002,Priya,Technology,Laptop,West,45000,1,8000,2026-01-12
2,1003,Kiran,Office Supplies,Paper,South,800,10,100,2026-01-15
3,1004,Sneha,Technology,Phone,North,18000,2,3000,2026-01-18
4,1005,Arjun,Furniture,Table,East,7000,1,900,2026-01-20

In [17]:
query = """
SELECT Customer_Name, Category, Sales, Profit
FROM superstore
LIMIT 10;
"""

pd.read_sql(query, conn)

DatabaseError: Execution failed on sql '
SELECT Customer_Name, Category, Sales, Profit
FROM superstore
LIMIT 10;
': no such column: Customer_Name

In [18]:
print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [19]:
pd.read_sql("PRAGMA table_info(superstore);", conn)

   cid           name     type  notnull dflt_value  pk
0    0       Order ID  INTEGER        0       None   0
1    1  Customer Name     TEXT        0       None   0
2    2       Category     TEXT        0       None   0
3    3   Sub-Category     TEXT        0       None   0
4    4         Region     TEXT        0       None   0
5    5          Sales  INTEGER        0       None   0
6    6       Quantity  INTEGER        0       None   0
7    7         Profit  INTEGER        0       None   0
8    8     Order Date     TEXT        0       None   0

In [20]:
pd.read_sql("SELECT * FROM superstore LIMIT 5;", conn)

,Order ID,Customer Name,Category,Sub-Category,Region,Sales,Quantity,Profit,Order Date
0,1001,Rahul,Furniture,Chair,East,2500,2,500,2026-01-10
1,1002,Priya,Technology,Laptop,West,45000,1,8000,2026-01-12
2,1003,Kiran,Office Supplies,Paper,South,800,10,100,2026-01-15
3,1004,Sneha,Technology,Phone,North,18000,2,3000,2026-01-18
4,1005,Arjun,Furniture,Table,East,7000,1,900,2026-01-20

In [21]:
print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [22]:
print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [23]:
pd.read_sql("SELECT * FROM superstore LIMIT 5;", conn)

,Order ID,Customer Name,Category,Sub-Category,Region,Sales,Quantity,Profit,Order Date
0,1001,Rahul,Furniture,Chair,East,2500,2,500,2026-01-10
1,1002,Priya,Technology,Laptop,West,45000,1,8000,2026-01-12
2,1003,Kiran,Office Supplies,Paper,South,800,10,100,2026-01-15
3,1004,Sneha,Technology,Phone,North,18000,2,3000,2026-01-18
4,1005,Arjun,Furniture,Table,East,7000,1,900,2026-01-20

In [24]:
pd.read_sql("PRAGMA table_info(superstore);", conn)

   cid           name     type  notnull dflt_value  pk
0    0       Order ID  INTEGER        0       None   0
1    1  Customer Name     TEXT        0       None   0
2    2       Category     TEXT        0       None   0
3    3   Sub-Category     TEXT        0       None   0
4    4         Region     TEXT        0       None   0
5    5          Sales  INTEGER        0       None   0
6    6       Quantity  INTEGER        0       None   0
7    7         Profit  INTEGER        0       None   0
8    8     Order Date     TEXT        0       None   0

In [25]:
print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [26]:
query = """
SELECT *
FROM superstore
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

,Order ID,Customer Name,Category,Sub-Category,Region,Sales,Quantity,Profit,Order Date
0,1001,Rahul,Furniture,Chair,East,2500,2,500,2026-01-10
1,1002,Priya,Technology,Laptop,West,45000,1,8000,2026-01-12
2,1003,Kiran,Office Supplies,Paper,South,800,10,100,2026-01-15
3,1004,Sneha,Technology,Phone,North,18000,2,3000,2026-01-18
4,1005,Arjun,Furniture,Table,East,7000,1,900,2026-01-20

In [27]:
columns = pd.read_sql("PRAGMA table_info(superstore);", conn)

columns

   cid           name     type  notnull dflt_value  pk
0    0       Order ID  INTEGER        0       None   0
1    1  Customer Name     TEXT        0       None   0
2    2       Category     TEXT        0       None   0
3    3   Sub-Category     TEXT        0       None   0
4    4         Region     TEXT        0       None   0
5    5          Sales  INTEGER        0       None   0
6    6       Quantity  INTEGER        0       None   0
7    7         Profit  INTEGER        0       None   0
8    8     Order Date     TEXT        0       None   0

In [28]:
print(columns["name"].tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [29]:
query = "SELECT * FROM superstore LIMIT 10;"

result = pd.read_sql(query, conn)

result

,Order ID,Customer Name,Category,Sub-Category,Region,Sales,Quantity,Profit,Order Date
0,1001,Rahul,Furniture,Chair,East,2500,2,500,2026-01-10
1,1002,Priya,Technology,Laptop,West,45000,1,8000,2026-01-12
2,1003,Kiran,Office Supplies,Paper,South,800,10,100,2026-01-15
3,1004,Sneha,Technology,Phone,North,18000,2,3000,2026-01-18
4,1005,Arjun,Furniture,Table,East,7000,1,900,2026-01-20

In [30]:
print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [31]:
pd.read_sql("PRAGMA table_info(superstore);", conn)

   cid           name     type  notnull dflt_value  pk
0    0       Order ID  INTEGER        0       None   0
1    1  Customer Name     TEXT        0       None   0
2    2       Category     TEXT        0       None   0
3    3   Sub-Category     TEXT        0       None   0
4    4         Region     TEXT        0       None   0
5    5          Sales  INTEGER        0       None   0
6    6       Quantity  INTEGER        0       None   0
7    7         Profit  INTEGER        0       None   0
8    8     Order Date     TEXT        0       None   0

In [32]:
query = """
SELECT *
FROM superstore
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

,Order ID,Customer Name,Category,Sub-Category,Region,Sales,Quantity,Profit,Order Date
0,1001,Rahul,Furniture,Chair,East,2500,2,500,2026-01-10
1,1002,Priya,Technology,Laptop,West,45000,1,8000,2026-01-12
2,1003,Kiran,Office Supplies,Paper,South,800,10,100,2026-01-15
3,1004,Sneha,Technology,Phone,North,18000,2,3000,2026-01-18
4,1005,Arjun,Furniture,Table,East,7000,1,900,2026-01-20

In [33]:
print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [34]:
-- Task 2: SQL for Data Extraction

-- 1. Display first 10 records
SELECT *
FROM superstore
LIMIT 10;

SyntaxError: invalid syntax (863237290.py, line 1)

In [35]:
query = """
SELECT *
FROM superstore
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

,Order ID,Customer Name,Category,Sub-Category,Region,Sales,Quantity,Profit,Order Date
0,1001,Rahul,Furniture,Chair,East,2500,2,500,2026-01-10
1,1002,Priya,Technology,Laptop,West,45000,1,8000,2026-01-12
2,1003,Kiran,Office Supplies,Paper,South,800,10,100,2026-01-15
3,1004,Sneha,Technology,Phone,North,18000,2,3000,2026-01-18
4,1005,Arjun,Furniture,Table,East,7000,1,900,2026-01-20

In [36]:
-- Task 2: SQL for Data Extraction

SELECT *
FROM superstore
LIMIT 10;

SyntaxError: invalid syntax (3063173740.py, line 1)

In [37]:
print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [38]:
import pandas as pd
import sqlite3

df = pd.read_csv("../data/cleaned_data.csv")

conn = sqlite3.connect("../data/superstore.db")

df.to_sql(
    "superstore",
    conn,
    if_exists="replace",
    index=False
)

print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [39]:
print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [40]:
print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [41]:
import pandas as pd

df = pd.read_csv("../data/cleaned_data.csv")

print(df.columns.tolist())

['Order ID', 'Customer Name', 'Category', 'Sub-Category', 'Region', 'Sales', 'Quantity', 'Profit', 'Order Date']

In [42]:
query = """
SELECT "Order ID", "Customer Name", Category, Sales, Profit
FROM superstore
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

   Order ID Customer Name         Category  Sales  Profit
0      1001         Rahul        Furniture   2500     500
1      1002         Priya       Technology  45000    8000
2      1003         Kiran  Office Supplies    800     100
3      1004         Sneha       Technology  18000    3000
4      1005         Arjun        Furniture   7000     900

In [43]:
query = """
SELECT "Order ID", "Customer Name", Category, Sales, Profit
FROM superstore
WHERE Sales > 1000
ORDER BY Sales DESC;
"""

result = pd.read_sql(query, conn)
result

   Order ID Customer Name    Category  Sales  Profit
0      1002         Priya  Technology  45000    8000
1      1004         Sneha  Technology  18000    3000
2      1005         Arjun   Furniture   7000     900
3      1001         Rahul   Furniture   2500     500

In [44]:
query = """
SELECT "Order ID", "Customer Name", Sales, Profit
FROM superstore
ORDER BY Sales DESC
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

   Order ID Customer Name  Sales  Profit
0      1002         Priya  45000    8000
1      1004         Sneha  18000    3000
2      1005         Arjun   7000     900
3      1001         Rahul   2500     500
4      1003         Kiran    800     100

In [45]:
query = """
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, conn)
result

          Category  Total_Sales
0       Technology        63000
1        Furniture         9500
2  Office Supplies          800

In [46]:
query = """
SELECT Category,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Category
ORDER BY Total_Profit DESC;
"""

result = pd.read_sql(query, conn)
result

          Category  Total_Profit
0       Technology         11000
1        Furniture          1400
2  Office Supplies           100

In [47]:
query = """
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category
HAVING SUM(Sales) > 100000
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, conn)
result

Empty DataFrame
Columns: [Category, Total_Sales]
Index: []

In [48]:
query = """
SELECT "Sub-Category",
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY "Sub-Category"
ORDER BY Total_Sales DESC
LIMIT 5;
"""

top_5_subcategories = pd.read_sql(query, conn)
top_5_subcategories

  Sub-Category  Total_Sales
0       Laptop        45000
1        Phone        18000
2        Table         7000
3        Chair         2500
4        Paper          800

In [49]:
query = """
SELECT Region,
       SUM(Sales) AS Total_Sales,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

sales_by_region = pd.read_sql(query, conn)
sales_by_region

  Region  Total_Sales  Total_Profit
0   West        45000          8000
1  North        18000          3000
2   East         9500          1400
3  South          800           100

In [50]:
query = """
SELECT "Customer Name",
       SUM(Sales) AS Total_Sales,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY "Customer Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

top_customers = pd.read_sql(query, conn)
top_customers

  Customer Name  Total_Sales  Total_Profit
0         Priya        45000          8000
1         Sneha        18000          3000
2         Arjun         7000           900
3         Rahul         2500           500
4         Kiran          800           100

In [51]:
query = """
CREATE TABLE IF NOT EXISTS region_info (
    Region TEXT PRIMARY KEY,
    Region_Type TEXT
);
"""

conn.execute(query)

region_data = [
    ("Central", "Domestic"),
    ("East", "Domestic"),
    ("South", "Domestic"),
    ("West", "Domestic")
]

conn.executemany(
    "INSERT OR IGNORE INTO region_info (Region, Region_Type) VALUES (?, ?)",
    region_data
)

conn.commit()

print("region_info table created successfully!")

region_info table created successfully!

In [52]:
pd.read_sql("SELECT * FROM region_info;", conn)

    Region Region_Type
0  Central    Domestic
1     East    Domestic
2    South    Domestic
3     West    Domestic

In [53]:
query = """
SELECT
    s.Region,
    r.Region_Type,
    SUM(s.Sales) AS Total_Sales,
    SUM(s.Profit) AS Total_Profit
FROM superstore s
INNER JOIN region_info r
    ON s.Region = r.Region
GROUP BY s.Region, r.Region_Type
ORDER BY Total_Sales DESC;
"""

result = pd.read_sql(query, conn)
result

  Region Region_Type  Total_Sales  Total_Profit
0   West    Domestic        45000          8000
1   East    Domestic         9500          1400
2  South    Domestic          800           100

In [54]:
query = """
SELECT
    "Order ID",
    "Customer Name",
    Sales,
    Profit
FROM superstore
WHERE Sales > (
    SELECT AVG(Sales)
    FROM superstore
)
ORDER BY Sales DESC;
"""

above_average_sales = pd.read_sql(query, conn)
above_average_sales.head(10)

   Order ID Customer Name  Sales  Profit
0      1002         Priya  45000    8000
1      1004         Sneha  18000    3000

In [55]:
query = """
WITH subcategory_sales AS (
    SELECT
        "Sub-Category",
        SUM(Sales) AS Total_Sales
    FROM superstore
    GROUP BY "Sub-Category"
)
SELECT
    "Sub-Category",
    Total_Sales
FROM subcategory_sales
ORDER BY Total_Sales DESC
LIMIT 5;
"""

top_subcategories = pd.read_sql(query, conn)
top_subcategories

  Sub-Category  Total_Sales
0       Laptop        45000
1        Phone        18000
2        Table         7000
3        Chair         2500
4        Paper          800

In [56]:
query = """
SELECT
    "Order ID",
    "Customer Name",
    Sales,
    ROW_NUMBER() OVER (ORDER BY Sales DESC) AS Sales_Row_Number
FROM superstore
ORDER BY Sales DESC
LIMIT 10;
"""

result = pd.read_sql(query, conn)
result

   Order ID Customer Name  Sales  Sales_Row_Number
0      1002         Priya  45000                 1
1      1004         Sneha  18000                 2
2      1005         Arjun   7000                 3
3      1001         Rahul   2500                 4
4      1003         Kiran    800                 5

In [57]:
query = """
WITH customer_sales AS (
    SELECT
        "Customer Name",
        SUM(Sales) AS Total_Sales
    FROM superstore
    GROUP BY "Customer Name"
)
SELECT
    "Customer Name",
    Total_Sales,
    RANK() OVER (ORDER BY Total_Sales DESC) AS Sales_Rank
FROM customer_sales
ORDER BY Sales_Rank
LIMIT 10;
"""

customer_ranking = pd.read_sql(query, conn)
customer_ranking

  Customer Name  Total_Sales  Sales_Rank
0         Priya        45000           1
1         Sneha        18000           2
2         Arjun         7000           3
3         Rahul         2500           4
4         Kiran          800           5

In [58]:
query = """
WITH monthly_sales AS (
    SELECT
        strftime('%Y-%m', "Order Date") AS Month,
        SUM(Sales) AS Total_Sales
    FROM superstore
    GROUP BY Month
)
SELECT
    Month,
    Total_Sales,
    LEAD(Total_Sales) OVER (ORDER BY Month) AS Next_Month_Sales
FROM monthly_sales
ORDER BY Month;
"""

next_month = pd.read_sql(query, conn)
next_month

     Month  Total_Sales Next_Month_Sales
0  2026-01        73300             None

In [59]:
query = """
CREATE VIEW IF NOT EXISTS regional_sales AS
SELECT
    Region,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit,
    SUM(Quantity) AS Total_Quantity
FROM superstore
GROUP BY Region;
"""

conn.execute(query)
conn.commit()

print("View created successfully!")

View created successfully!

In [60]:
query = """
SELECT *
FROM regional_sales
ORDER BY Total_Sales DESC;
"""

regional_sales = pd.read_sql(query, conn)
regional_sales

  Region  Total_Sales  Total_Profit  Total_Quantity
0   West        45000          8000               1
1  North        18000          3000               2
2   East         9500          1400               3
3  South          800           100              10

In [61]:
query = """
SELECT
    "Sub-Category",
    SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY "Sub-Category"
ORDER BY Total_Sales DESC
LIMIT 5;
"""

q1 = pd.read_sql(query, conn)
q1

  Sub-Category  Total_Sales
0       Laptop        45000
1        Phone        18000
2        Table         7000
3        Chair         2500
4        Paper          800

In [62]:
query = """
SELECT
    strftime('%Y-%m', "Order Date") AS Month,
    SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Month
ORDER BY Month;
"""

q2 = pd.read_sql(query, conn)
q2

     Month  Total_Sales
0  2026-01        73300

In [63]:
query = """
SELECT
    "Customer Name",
    SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY "Customer Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

q3 = pd.read_sql(query, conn)
q3

  Customer Name  Total_Sales
0         Priya        45000
1         Sneha        18000
2         Arjun         7000
3         Rahul         2500
4         Kiran          800

In [64]:
query = """
SELECT
    Region,
    SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

q4 = pd.read_sql(query, conn)
q4

  Region  Total_Sales
0   West        45000
1  North        18000
2   East         9500
3  South          800

In [65]:
query = """
SELECT
    Category,
    SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Category
ORDER BY Total_Profit DESC;
"""

q5 = pd.read_sql(query, conn)
q5

          Category  Total_Profit
0       Technology         11000
1        Furniture          1400
2  Office Supplies           100

In [66]:
query = """
SELECT
    "Customer Name",
    SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY "Customer Name"
ORDER BY Total_Profit DESC
LIMIT 10;
"""

q6 = pd.read_sql(query, conn)
q6

  Customer Name  Total_Profit
0         Priya          8000
1         Sneha          3000
2         Arjun           900
3         Rahul           500
4         Kiran           100

In [67]:
query = """
SELECT
    "Sub-Category",
    SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY "Sub-Category"
ORDER BY Total_Sales DESC
LIMIT 1;
"""

q7 = pd.read_sql(query, conn)
q7

  Sub-Category  Total_Sales
0       Laptop        45000

In [68]:
query = """
SELECT
    AVG(Order_Sales) AS Average_Order_Sales
FROM (
    SELECT
        "Order ID",
        SUM(Sales) AS Order_Sales
    FROM superstore
    GROUP BY "Order ID"
);
"""

q8 = pd.read_sql(query, conn)
q8

   Average_Order_Sales
0              14660.0

In [69]:
query = """
SELECT
    "Order ID",
    "Customer Name",
    SUM(Sales) AS Order_Sales
FROM superstore
GROUP BY "Order ID", "Customer Name"
HAVING SUM(Sales) > (
    SELECT AVG(Order_Sales)
    FROM (
        SELECT
            "Order ID",
            SUM(Sales) AS Order_Sales
        FROM superstore
        GROUP BY "Order ID"
    )
)
ORDER BY Order_Sales DESC;
"""

q9 = pd.read_sql(query, conn)
q9.head(10)

   Order ID Customer Name  Order_Sales
0      1002         Priya        45000
1      1004         Sneha        18000

In [70]:
query = """
SELECT
    strftime('%Y-%m', "Order Date") AS Month,
    SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Month
ORDER BY Month;
"""

q10 = pd.read_sql(query, conn)
q10

     Month  Total_Profit
0  2026-01         12500